### ISSUE TITLE
OSX binary: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0o-de-lally** [checkr/go-sync-mongo#1]
Using OSX binary, with Sync operation yields this error:
___________________________

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xa58bf]

goroutine 1 [running]:
panic(0x443ea0, 0xc4200100a0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/checkr/go-sync-mongo/db.(*Connection).SyncOplog(0x0, 0x0, 0xc4200ddb88, 0x1)
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/db/db.go:132 +0xaf
github.com/checkr/go-sync-mongo/cmd.glob..func2(0x6d7ee0, 0xc4201222a0, 0x0, 0xe)
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/cmd/sync.go:43 +0x38a
github.com/spf13/cobra.(*Command).execute(0x6d7ee0, 0xc4201221c0, 0xe, 0xe, 0x6d7ee0, 0xc4201221c0)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x6d7aa0, 0xc42006c058, 0x0, 0xc4200ddf18)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0x6d7aa0, 0x0, 0x0)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:681 +0x2b
github.com/checkr/go-sync-mongo/cmd.Execute()
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/cmd/root.go:46 +0x31
main.main()
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/main.go:20 +0x14

**Comment by Gugic** [comment]
+1 for 'status' on OSX

Eugenys-MBP:darwin-amd64 Gugic$ sudo ./go-sync-mongo status --src "mongodb://host-01:27017,host-01:27018/api?replicaSet=rs0" --dst "mongodb://host-02:27017,host-2:27018/api?replicaSet=rs0"
Password:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xa50a7]

goroutine 1 [running]:
panic(0x443ea0, 0xc4200140b0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/checkr/go-sync-mongo/db.(*Connection).Databases(0x0, 0x9, 0xc4200e1a48, 0x1, 0x1, 0x6aae20)
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/db/db.go:83 +0x37
github.com/checkr/go-sync-mongo/cmd.glob..func1(0x6d7cc0, 0xc420056b40, 0x0, 0x4)
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/cmd/status.go:54 +0x3a0
github.com/spf13/cobra.(*Command).execute(0x6d7cc0, 0xc420056b00, 0x4, 0x4, 0x6d7cc0, 0xc420056b00)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:636 +0x443
github.com/spf13/cobra.(*Command).ExecuteC(0x6d7aa0, 0xc42000c118, 0x0, 0xc4200e1f18)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:722 +0x367
github.com/spf13/cobra.(*Command).Execute(0x6d7aa0, 0x0, 0x0)
	/Users/saso/Development/go/src/github.com/spf13/cobra/command.go:681 +0x2b
github.com/checkr/go-sync-mongo/cmd.Execute()
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/cmd/root.go:46 +0x31
main.main()
	/Users/saso/Development/go/src/github.com/checkr/go-sync-mongo/main.go:20 +0x14

**Comment by Gugic** [comment]
same on linux.

Also (if it helps) - tried to execute from sources and got more readab;e stack

[shingarev@HOST go-sync-mongo]$ go run ./main.go status --src "mongodb://host-01:27017,host-01:27018/api?replicaSet=rs0" --dst "mongodb://host-02:27017,host-02:27018/api?replicaSet=rs0"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x4b8753]

goroutine 1 [running]:
github.com/checkr/go-sync-mongo/db.(*Connection).Databases(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shingarev/go/src/github.com/checkr/go-sync-mongo/db/db.go:83 +0x53
github.com/checkr/go-sync-mongo/cmd.glob.func1(0xc97aa0, 0xc820072900, 0x0, 0x4)
	/home/shingarev/go/src/github.com/checkr/go-sync-mongo/cmd/status.go:54 +0x4eb
github.com/spf13/cobra.(*Command).execute(0xc97aa0, 0xc8200728c0, 0x4, 0x4, 0x0, 0x0)
	/home/shingarev/go/src/github.com/spf13/cobra/command.go:636 +0x8f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc97880, 0xc97aa0, 0x0, 0x0)
	/home/shingarev/go/src/github.com/spf13/cobra/command.go:722 +0x56b
github.com/spf13/cobra.(*Command).Execute(0xc97880, 0x0, 0x0)
	/home/shingarev/go/src/github.com/spf13/cobra/command.go:681 +0x2d
github.com/checkr/go-sync-mongo/cmd.Execute()
	/home/shingarev/go/src/github.com/checkr/go-sync-mongo/cmd/root.go:46 +0x27
main.main()
	/home/shingarev/go/src/github.com/checkr/go-sync-mongo/main.go:20 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1721 +0x1

goroutine 66 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201bc000, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 50 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201b6000, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 14 [sleep]:
time.Sleep(0x1dcd6500)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc820212000)
	/home/shingarev/go/src/gopkg.in/mgo.v2/cluster.go:386 +0x484
created by gopkg.in/mgo%2ev2.newCluster
	/home/shingarev/go/src/gopkg.in/mgo.v2/cluster.go:78 +0x1d0

goroutine 29 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201142a0, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 7 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201f6000, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 45 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc820218000, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 87 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201f61c0, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 103 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8202180e0, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160

goroutine 32 [sleep]:
time.Sleep(0x37e11d600)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc820114380, 0x1)
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:301 +0x1b0
created by gopkg.in/mgo%2ev2.newServer
	/home/shingarev/go/src/gopkg.in/mgo.v2/server.go:89 +0x160
exit status 2

**Comment by iamsaso** [comment]
You are missing `--src-username *** --src-password ***` and `--dst-username *** --dst-password ***`

**Comment by Gugic** [comment]
And if there is no username and password? (Test environment without
protection, prod - x.509)

**Comment by iamsaso** [comment]
Found the cause of the problem. The problem is that SSL was enabled by default and it caused a connection failure. I disabled it by default now and pushed changes to master and created a v1.1 release.

You can now decide to enable SSL when needed. Empty username and password should work for any host too as they get set as empty by default.

**Comment by Gugic** [comment]
@sasso ok, thanks, i checked it, now works just like it should be. Thank you.
