### ISSUE TITLE
How do I know from which timestamp to start restoring and tailing after go-sync-mongo restarts

### ISSUE THREAD

**Issue by hongshibao** [checkr/go-sync-mongo#3]
Does go-sync-mongo has timestamp record (e.g. in logs)? So that I can continue restoring data from that timestamp (--since param) after go-sync-mongo process restarts.

**Comment by iamsaso** [comment]
You will need to get the latest id that was inserted and get timestamp out of it I think. It's also safe to go back a day from that timestamp as inserts are idempotent.

**Comment by hongshibao** [comment]
Got it. Thanks.
